spring.application.name=demo
server.port=8081

# AWS RDS 데이터베이스 연결
spring.datasource.url=jdbc:mysql://database-1.croiqao0m2on.ap-northeast-2.rds.amazonaws.com:3306/demo?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=cicd1234!
# JPA 및 Hibernate 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true